reiniergs/polyfill-service

.travis.yml
=> add travis CI first commit

.travis.yml, pom.xml, readme.md, src/main/java/HelloWorld.java
=> add code coverage Jacoco plugin

pom.xml, src/main/java/org/polyfill/Services/UserAgentParserService.java, src/main/java/org/polyfill/components/UserAgentImpl.java, src/main/java/org/polyfill/interfaces/ConfigLoaderService.java, src/main/java/org/polyfill/services/JSONConfigLoaderService.java, src/main/java/org/polyfill/services/MapUtilService.java, src/test/java/org/polyfill/services/JSONConfigLoaderServiceTest.java, src/test/java/org/polyfill/services/MapUtilServiceTest.java, src/test/java/org/polyfill/services/SemVerUtilServiceTest.java, src/test/java/org/polyfill/services/UserAgentParserServiceTest.java
Fix file structure under test folder
- Rename ConfigLoaderServiceInterface to ConfigLoaderService based on other interfaces' names
- Remove userAgent folder
New stuff
- Add simple logging to slf4j
- New util for printing Map for debugging/testing
Cleanup
- Clean up UserAgentParser and its tests
=> Mostly cleanups

pom.xml, src/main/webapp/WEB-INF/web.xml, src/main/webapp/landing.html
https://github.com/reiniergs/polyfill-service/issues/44
=> Access javadoc from URL

src/main/java/org/polyfill/components/Polyfill.java, src/main/java/org/polyfill/controllers/PolyfillController.java, src/main/java/org/polyfill/views/PolyfillsView.java
=> move polyfill concatenation into the PolyfillView

src/main/java/org/polyfill/components/Polyfill.java, src/main/java/org/polyfill/interfaces/PolyfillQueryService.java, src/main/java/org/polyfill/services/PreSortPolyfillQueryService.java, src/test/java/org/polyfill/components/PolyfillTest.java
Update docs
Test for polyfill wrapper
=> Added polyfill detect source support

readme.md
1. Fixes #57 
2. Added a badge for license and adding steps to run locally
=> Fixing code coverage badge and modifying readme

src/main/java/org/polyfill/Interfaces/UserAgent.java, src/main/java/org/polyfill/components/UserAgentImpl.java, src/main/java/org/polyfill/controllers/PolyfillController.java, src/main/java/org/polyfill/interfaces/ConfigLoaderService.java, src/main/java/org/polyfill/interfaces/UserAgentParserService.java, src/main/java/org/polyfill/interfaces/VersionUtilService.java, src/main/java/org/polyfill/services/JSONConfigLoaderService.java, src/main/java/org/polyfill/services/SemVerUtilService.java, src/main/java/org/polyfill/services/UADetectorBasedUserAgentParserService.java, src/test/java/org/polyfill/controllers/PolyfillControllerTest.java, src/test/java/org/polyfill/services/JSONConfigLoaderServiceTest.java, src/test/java/org/polyfill/services/UADetectorBasedUserAgentParserServiceTest.java
- Added interfaces and renamed implementation classes
- Add @Override. This will inherit docs from interface.
- Extra: Fix JSONConfigLoaderTest's tests
=> Cleanup interfaces

polyfills/browserAliases.json, src/main/java/org/polyfill/components/UserAgentImpl.java, src/main/java/org/polyfill/controllers/PolyfillController.java, src/main/java/org/polyfill/services/UADetectorBasedUserAgentParserService.java, src/test/java/org/polyfill/configurations/MockBrowserAliasesConfig.java, src/test/java/org/polyfill/services/UADetectorBasedUserAgentParserServiceTest.java
- add normalized ua string parse logic
- add support to query param ua override
- tests
- fix yandex browser alias
=> Add support to query param ua override

src/main/java/org/polyfill/components/Polyfill.java, src/main/java/org/polyfill/controllers/WebAppController.java
=> Move out presentation logic from the polyfill class

src/main/java/org/polyfill/components/Polyfill.java, src/main/java/org/polyfill/controllers/PolyfillController.java, src/main/java/org/polyfill/controllers/UACheckerController.java, src/main/java/org/polyfill/services/PreSortPolyfillQueryService.java, src/main/pages/handlebars/userAgentDetector.hbs
Makes PolyfillQueryService much cleaner and easier to work with.
This is necessary for adding functionalities later on. Needed for the test runner work.
Also cleaned up some random stuff.
=> Refactoring. Mainly for query service

src/main/java/org/polyfill/controllers/PolyfillController.java
@scottmo review this option...
=> Merging minified and regular actions into one.

pom.xml
Put login info in ~/.m2/settings.xml to deploy
For now we just deploy poms and jars to repo.auraframework.org
=> Fix deployment url

.travis.yml, deploy.sh, settings.xml
@reiniergs No merge. Need to test this first after you added the env variables.
The only thing I am not sure is this part:
if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]
=> [Review Only] Use travis for auto deployment

api/src/main/java/org/polyfill/api/components/Query.java, api/src/main/java/org/polyfill/api/services/PreSortPolyfillService.java, api/src/main/java/org/polyfill/api/services/XMLQueryLoaderService.java, api/src/test/java/org/polyfill/api/services/XMLQueryLoaderServiceTest.java, api/src/test/resources/queries/query-config-flags.xml, api/src/test/resources/queries/query-config.xml, rest/src/main/java/org/polyfill/rest/controllers/PolyfillController.java
Added some more stuff to improve usability of xml query config.
Added these to make aura example more acceptable.
=> Added features to exclude and global flags for query config xml.

api/src/main/java/org/polyfill/api/services/XMLQueryLoaderService.java, api/src/test/java/org/polyfill/api/services/XMLQueryLoaderServiceTest.java, api/src/test/resources/queries/query-config-flags.xml
minified & loadOnUnknownUA
Let me know if they should be named differently
I am also wondering whether we should do minify by default
Will need a better way to manage the values of xml fields
=> Two more fields for query xml config

README.md
Hopefully this time will be fixed
=> Link fix attempt 3 = - =

api/pom.xml, perf/pom.xml, pom.xml, rest/pom.xml, web/pom.xml
Path incremented as new feature was introduced (custom polyfills registration).
=> Update version to 0.10.0.

README.md, polyfill-service-api/polyfills/Node/prototype/contains/config.json, polyfill-service-api/polyfills/Node/prototype/contains/detect.js, polyfill-service-api/polyfills/Node/prototype/contains/polyfill.js, polyfill-service-api/polyfills/Node/prototype/contains/tests.js
Add missing polyfill (Node. My global git ignore excluded this = =)
Update README links.
=> Fix rename package bugs

polyfill-service-api/src/main/java/org/polyfillservice/api/components/TSort.java, polyfill-service-api/src/test/java/org/polyfillservice/api/components/FeatureTest.java, polyfill-service-api/src/test/java/org/polyfillservice/api/components/TSortTest.java, polyfill-service-api/src/test/java/org/polyfillservice/api/services/PolyfillsOutputServiceTest.java, polyfill-service-api/src/test/java/org/polyfillservice/api/services/SemVerUtilServiceTest.java, polyfill-service-api/src/test/java/org/polyfillservice/api/services/UADetectorAdapterParserServiceTest.java, polyfill-service-api/src/test/java/org/polyfillservice/api/utils/TestingUtil.java, polyfill-service-perf/src/main/java/org/polyfillservice/perf/configurations/RunnerConfig.java, pom.xml
More tests + update some tests
=> Test updates

polyfill-service-api/polyfills/Object/getPrototypeOf/config.json, polyfill-service-api/polyfills/Object/getPrototypeOf/detect.js, polyfill-service-api/polyfills/Object/getPrototypeOf/polyfill.js, polyfill-service-api/polyfills/String/fromCodePoint/config.json, polyfill-service-api/polyfills/String/fromCodePoint/detect.js, polyfill-service-api/polyfills/String/fromCodePoint/polyfill.js, polyfill-service-api/polyfills/String/prototype/codePointAt/config.json, polyfill-service-api/polyfills/String/prototype/codePointAt/detect.js, polyfill-service-api/polyfills/String/prototype/codePointAt/polyfill.js, polyfill-service-api/polyfills/Symbol/iterator/config.json, polyfill-service-api/polyfills/Symbol/iterator/polyfill.js, polyfill-service-api/polyfills/Symbol/polyfill.js, polyfill-service-api/polyfills/Symbol/toStringTag/config.json, polyfill-service-api/polyfills/Symbol/toStringTag/polyfill.js
Updated the following for IE11:
- Object.getPrototypeOf
- Symbol
Added the following to support Symbol.iterator:
- String.prototype.codePointAt
- String.fromCodePoint
=> Polyfills updates

polyfill-service-api/pom.xml, polyfill-service-perf/pom.xml, polyfill-service-rest/pom.xml, polyfill-service-web/pom.xml, pom.xml
Changes:
- Fixed bug in Symbol.toStringTag polyfill
=> Upgrade version to 1.2.1
